#!/usr/bin/env bash
# Script that extends the previous exercise command
# Displays lines containing the word "bash", allowing you to easily get the PID of your Bash process
# Does not use pgrep
# shellcheck disable=SC2009

# Execute the previous exercise script to list all processes
./1-list_your_processes |

# Use grep command to filter lines containing the word "bash"
grep "bash"
