#!/usr/bin/env bash
# This script iterates from 1 to 10 and displays different messages for specific iterations:
# - "bad luck" is displayed on the 4th iteration
# - "good luck" is displayed on the 8th iteration
# - "Best School" is displayed for the other iterations

i="0"

while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]; then
        echo "bad luck"
    elif [ $i -eq 7 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done