#!/usr/bin/env bash
# Bash script that provides information about the `school` file.

if [ -e "school" ]
then
  echo "The 'school' file exists."
  if [ -s "school" ]
  then
    echo "The 'school' file is not empty."
  else
    echo "The 'school' file is empty."
  fi

  if [ -f "school" ]
  then
    echo "The 'school' file is a regular file."
  fi
else
  echo "The 'school' file does not exist."
fi